import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { GetServerSideProps } from 'next';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

interface Post {
  id: number;
  title: { rendered: string };
  content: { rendered: string };
  featured_media: number | null;
  featured_media_url?: string;
}

interface HomeProps {
  posts: Post[];
}

const Home: NextPage<HomeProps> = ({ posts }) => {
  const [loading, setLoading] = useState(false);

  return (
    <div className={`${styles.container} bg-gray-900 text-white min-h-screen`}>
      <Head>
        <title>Animal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto p-6">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-4xl font-bold text-center text-yellow-400">All Posts</h1>
        </div>

        <div className="space-y-12">
          {posts.map((post) => (
            <div key={post.id} className="border border-gray-700 rounded-lg p-6 shadow-lg hover:bg-gray-800 transition duration-300">
              {/* Featured Image */}
              {post.featured_media_url && (
                <div className="mb-6">
                  <Image
                    src={post.featured_media_url || '/default-thumbnail.jpg'}
                    alt={post.title.rendered || 'Post Image'}
                    width={800}
                    height={450}
                    className="rounded-md"
                  />
                </div>
              )}
              <h2 className="text-3xl font-semibold mb-4 text-yellow-300">{post.title.rendered}</h2>
              <div
                className="text-gray-400"
                dangerouslySetInnerHTML={{ __html: post.content.rendered }} // Use full content
              />
            </div>
          ))}
        </div>
      </main>

      <footer className="bg-gray-800 p-4 mt-12 text-center text-gray-400">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex justify-center items-center space-x-2"
        >
          Powered by Chhay{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

// Fetch posts server-side on each request
export const getServerSideProps: GetServerSideProps = async () => {
  const wordpressAPIUrl = 'https://freshnew.online/wp-json/wp/v2/posts';
  const res = await fetch(wordpressAPIUrl);
  const posts = await res.json();

  // Fetch featured media for each post
  const postsWithMedia = await Promise.all(
    posts.map(async (post) => {
      if (post.featured_media) {
        const mediaResponse = await fetch(
          `https://freshnew.online/wp-json/wp/v2/media/${post.featured_media}`
        );
        const media = await mediaResponse.json();
        post.featured_media_url = media.source_url;
      }
      return post;
    })
  );

  return {
    props: {
      posts: postsWithMedia,
    },
  };
};

export default Home;
