import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from "react"
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [posts, setPosts] = useState<any[]>([]);
  const wordpressAPIUrl = "https://freshnew.online/wp-json/wp/v2/posts"; // Replace with your WordPress site URL

  useEffect(() => {
    fetch(wordpressAPIUrl)
      .then((res) => res.json())
      .then((data) => setPosts(data))
      .catch((err) => console.error("Error fetching posts from WordPress:", err));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Animal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-4xl font-bold mb-6">Latest Posts</h1>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {posts.map((post) => (
            <div key={post.id} className="border rounded-lg p-4 shadow-lg">
              <h2 className="text-2xl font-semibold mb-2">{post.title.rendered}</h2>
              <p className="text-gray-600" dangerouslySetInnerHTML={{ __html: post.excerpt.rendered }}></p>
              <a href={`/post/${post.slug}`} className="text-blue-500 mt-2 block">Read More</a>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Chhay{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home;
