import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [posts, setPosts] = useState<any[]>([]);
  const router = useRouter();
  const wordpressAPIUrl = 'https://freshnew.online/wp-json/wp/v2/posts'; // Remove pagination for all posts

  useEffect(() => {
    fetch(wordpressAPIUrl)
      .then((res) => res.json())
      .then((data) => setPosts(data))
      .catch((err) => console.error('Error fetching posts from WordPress:', err));
  }, []);

  const handleHomeClick = () => {
    router.push('/'); // Navigate to the home page
  };

  return (
    <div className={`${styles.container} bg-gray-900 text-white min-h-screen`}>
      <Head>
        <title>Animal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto p-6">
        <div className="flex justify-between items-center mb-6">
          <button
            onClick={handleHomeClick}
            className="bg-yellow-400 text-black px-4 py-2 rounded-md hover:bg-yellow-300 transition duration-300"
          >
            Home
          </button>
          <h1 className="text-4xl font-bold text-center text-yellow-400">All Posts</h1>
        </div>

        <div className="space-y-12">
          {posts.map((post) => (
            <div key={post.id} className="border border-gray-700 rounded-lg p-6 shadow-lg hover:bg-gray-800 transition duration-300">
              {/* Featured Image */}
              {post.featured_media_url && (
                <div className="mb-6">
                  <Image
                    src={post.featured_media_url || '/default-thumbnail.jpg'}
                    alt={post.title.rendered || 'Post Image'}
                    width={800}
                    height={450}
                    className="rounded-md"
                  />
                </div>
              )}
              <h2 className="text-3xl font-semibold mb-4 text-yellow-300">{post.title.rendered}</h2>
              <div
                className="text-gray-400"
                dangerouslySetInnerHTML={{ __html: post.content.rendered }} // Use full content
              />
            </div>
          ))}
        </div>
      </main>

      <footer className="bg-gray-800 p-4 mt-12 text-center text-gray-400">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex justify-center items-center space-x-2"
        >
          Powered by Chhay{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
